sudo: required
services:
    - docker

before_install:
    - docker build -t kaanhangunay/react-docker -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kaanhangunay/react-docker npm run test

language: generic 